---

- name: detect binary file for registry  - {{ registry_ui_local_tmp_directory }}/registry-ui
  become: false
  delegate_to: "{{ registry_ui_delegate_to }}"
  stat:
    path: "{{ registry_ui_local_tmp_directory }}/registry-ui"
  register: stat_file_binary

- name: copy binary files
  block:
    - name: propagate registry binaries
      copy:
        src: "{{ registry_ui_local_tmp_directory }}/registry-ui"
        dest: "{{ registry_ui_install_path }}/registry-ui"
        mode: 0755
        owner: "{{ registry_ui_system_user }}"
        group: "{{ registry_ui_system_group }}"
        remote_src: "{{ 'true' if registry_ui_direct_download else 'false' }}"

    - name: propagate static files
      copy:
        src: "{{ registry_ui_local_tmp_directory }}/{{ item }}/"
        dest: "{{ registry_ui_data_dir }}/{{ item }}/"
        mode: 0644
        owner: "{{ registry_ui_system_user }}"
        group: "{{ registry_ui_system_group }}"
        remote_src: "{{ 'true' if registry_ui_direct_download else 'false' }}"
      loop:
        - static
        - templates
      notify:
        - reload registry-ui

  when:
    - stat_file_binary.stat.exists

- name: make files executable
  file:
    path: "{{ registry_ui_install_path }}/registry-ui"
    mode: 0755
    owner: "{{ registry_ui_system_user }}"
    group: "{{ registry_ui_system_group }}"


- name: create local facts
  template:
    src: ansible_facts.j2
    dest: /etc/ansible/facts.d/registry-ui.fact
    mode: 0755

# - name: create registry data directory
#   file:
#     state: directory
#     path: "{{ registry_ui_data_dir }}"
#     mode: 0770
#     owner: "{{ registry_ui_system_user }}"
#     group: "{{ registry_ui_system_group }}"

- name: create link to binary
  file:
    src: "{{ registry_ui_install_path }}/registry-ui"
    dest: "/usr/bin/registry-ui"
    state: link
    force: true
    follow: false
  notify:
    - restart registry-ui

- name: systemd
  block:
    - name: create systemd service unit
      template:
        src: "init/systemd/registry-ui.service.j2"
        dest: "{{ systemd_lib_directory }}/registry-ui.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart registry-ui

    - name: create registry run configuration
      template:
        src: "registry-ui.j2"
        dest: "{{ registry_ui_defaults_directory }}/registry-ui"
        force: true
        owner: root
        group: "{{ registry_ui_system_group }}"
        mode: 0640
      notify:
        - validate config
        - reload registry-ui
  when:
    - ansible_service_mgr | lower == "systemd"

- name: openrc
  block:
    - name: create openrc service configuration
      template:
        src: "init/openrc/conf.d/registry-ui.j2"
        dest: "/etc/conf.d/registry-ui"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      template:
        src: "init/openrc/init.d/registry-ui.j2"
        dest: "/etc/init.d/registry-ui"
        owner: root
        group: root
        mode: 0750
  when:
    - ansible_service_mgr | lower == "openrc"

...
