---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  package:
    update_cache: true

- name: define delegate instance for download handling
  set_fact:
    registry_ui_delegate_to: "{{ ansible_host }}"
    registry_ui_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/registry', true) }}/{{ registry_ui_version }}"
  when:
    - registry_ui_direct_download

- name: install dependency
  package:
    name: "{{ registry_ui_requirements }}"
    state: present
  when:
    - registry_ui_requirements | default([]) | count > 0

- name: get latest release
  block:
    - name: get latest release
      uri:
        url: "https://api.github.com/repos/distribution/distribution/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      # no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: set registry version to {{ _latest_release.json.tag_name[1:] }}
      set_fact:
        registry_ui_version: "{{ _latest_release.json.tag_name[1:] }}"
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - registry_ui_version == "latest"

- name: detect our installation path '{{ registry_ui_install_path | dirname }}'
  stat:
    path: "{{ registry_ui_install_path | dirname }}"
    get_checksum: false
  register: stat_registry_ui_path
  ignore_errors: true

- name: old installation
  block:
    - name: stop old service
      service:
        name: registry
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      file:
        state: absent
        path: /etc/systemd/system/registry.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed registry
      file:
        state: absent
        path: "{{ stat_registry_ui_path.stat.path }}"
  when:
    - stat_registry_ui_path is defined
    - stat_registry_ui_path.stat is defined
    - stat_registry_ui_path.stat.isdir is defined
    - not stat_registry_ui_path.stat.isdir

- name: flush handlers
  meta: flush_handlers

- name: detect installed registry binary
  stat:
    path: "{{ registry_ui_install_path }}/registry-ui"
  register: stat_registry_ui_binary

- name: create download directory
  become: false
  delegate_to: "{{ registry_ui_delegate_to }}"
  file:
    path: "{{ registry_ui_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: user and group handling
  block:
    - name: create registry group
      group:
        name: "{{ registry_ui_system_group }}"
        state: present
        system: true

    - name: create registry user
      user:
        name: "{{ registry_ui_system_user }}"
        groups: "{{ registry_ui_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: "{{ registry_ui_data_dir }}"
  when:
    - registry_ui_system_user != "root"

- name: create install directory
  file:
    path: "{{ registry_ui_install_path }}"
    state: directory
    owner: "{{ registry_ui_system_user }}"
    group: "{{ registry_ui_system_group }}"
    mode: 0755

- name: create ansible local facts directory
  file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: merge registry configuration between defaults and custom
  set_fact:
    registry_ui_service: "{{ registry_ui_defaults_service | combine( registry_ui_service, recursive=True) }}"
    registry_ui_listen: "{{ registry_ui_defaults_listen | combine( registry_ui_listen, recursive=True) }}"
    registry_ui_registry: "{{ registry_ui_defaults_registry | combine( registry_ui_registry, recursive=True) }}"
    registry_ui_event: "{{ registry_ui_defaults_event | combine( registry_ui_event, recursive=True) }}"
    registry_ui_cache: "{{ registry_ui_defaults_cache | combine( registry_ui_cache, recursive=True) }}"
    registry_ui_admins: "{{ registry_ui_defaults_admins | combine( registry_ui_admins, recursive=True) }}"
    registry_ui_purge: "{{ registry_ui_defaults_purge | combine( registry_ui_purge, recursive=True) }}"

...
